# Allow different types of PvP in the game
allow:
  crystal-pvp: false
  bed-pvp: false
  anchor-pvp: false

# Bypass configurations.
bypass:
  # Bypass item checks.
  item-check:
    # Permission to bypass item checks.
    permission: "generalpvp.bypass.item-check"
  # Bypass potion checks.
  potion-check:
    # Permission to bypass potion checks.
    permission: "generalpvp.bypass.potion-check"
  # Bypass enchantment checks.
  enchantment-check:
    # Permission to bypass enchantment checks.
    permission: "generalpvp.bypass.enchantment-check"

# Cooldown configurations.
cooldowns:
  # Minimum time in ticks between pearl throws.
  pearl: 300 # 15 seconds

# Item configurations.
items:
  # Drop extra on ground.
  drop-excess: true
  # If ENCHANTED_GOLDEN_APPLE should be treated like GOLDEN_APPLE.
  # If true, just put the material as GOLDEN_APPLE.
  all-golden-apples-similar: true
  totems:
    material: TOTEM_OF_UNDYING
    max-amount: 1
  pearls:
    material: ENDER_PEARL
    max-amount: 16
  gapples:
    material: GOLDEN_APPLE
    max-amount: 16
  webs:
    material: COBWEB
    max-amount: 64

# Potion configurations.
potions:
  #strength:
  #  type: STRENGTH
  #  amplifier: -1 # -1 means any strength level
  strength:
    type: STRENGTH
    amplifier: 2 # STRENGTH II and above is blocked
  speed:
    type: SWIFTNESS
    amplifier: 2 # SPEED II and above is blocked

# Enchantment configurations.
enchantments:
  protection:
    type: "protection"
    amplifier: 4 # PROTECTION IV and above is blocked